{
  'name': 'kami_form',
  'category': 'Services',
  'summary': 'KAMI CO. External Forms',
  'version': '1.0',
  'license': 'GPL-3 or any later version',
  'depends': ['base', 'project', 'website','web','kami_sm','helpdesk_mgmt','helpdesk_mgmt_project','helpdesk_mgmt_rating','helpdesk_mgmt_sla','helpdesk_type'],
  'data': [
      'templates/project_data.xml',
      'templates/forms_success_page.xml',
      'templates/audiovisual.xml',
      'templates/project_data.xml',
      'templates/mala_tecnica.xml',
      'templates/fachada.xml',
      'templates/planejamento_campanha_marketing.xml',
      'templates/romaneio.xml',
      'templates/invasao_truss.xml',
      'templates/criativo.xml',
      'templates/educacional_mvp.xml',
      'templates/promotoria_freelancer.xml',
      'templates/campanha_mkt.xml',
      'templates/solicitacao_redes_sociais.xml',
      'templates/cursos_kamico.xml',
      'templates/formulario_rh.xml',
      'templates/educacional_content.xml',
      'templates/novos_produtos.xml',
      'templates/trade_marketing.xml',
      'templates/kamihelpdesk.xml',
      'templates/dossie.xml',
      'templates/kamism.xml',
      'templates/teste.xml',
      'templates/viagem.xml',
      'templates/pagamento.xml',
  ],
  'installable': True,
  'auto_install': False,
  'application': False,
  'author': 'Gustavo',
}
