{
  'name': 'remake',
  'category': 'Services',
  'summary': 'Kamico Service Manager',
  'version': '1.0',
  'license': 'GPL-3 or any later version',
  'depends': ['base', 'project', 'website','web','kami_sm'],
  'data': [
      
      'templates/forms_success_page.xml',
      'templates/audiovisual.xml',
      'templates/project_data.xml',
      'templates/mala_tecnica.xml',
      'templates/fachada.xml',
      'templates/planejamento_campanha_marketing.xml',
      'templates/romaneio.xml',
      'templates/invasao_truss.xml',
      'templates/criativo.xml',
      'templates/educacional_mvp.xml',
      'templates/promotoria_freelancer.xml',
      'templates/campanha_mkt.xml',
  ],
  'installable': True,
  'auto_install': False,
  'application': False,
  'author': 'Gustavo',
}
